### ISSUE TITLE
Is this Fake?

### ISSUE THREAD

**Issue by nspsck** [WeActTC/WeAct_F411CE#7]
Hi, I noticed that I got some random STM32F411 from this store:

https://de.aliexpress.com/item/4001062944589.html?spm=a2g0o.store_pc_allProduct.8148356.4.3b7c2e1dKCRWnw&pdp_npi=3%40dis%21CHF%21CHF%201.54%21CHF%201.24%21%21%21%21%21%402101f4a016841919341276246e18e2%2112000017442725896%21sh%21CH%214690143121

Everything looks identical, but it came with both the boards and pins in the same pakage. Could this be a fake product?

best regards

**Comment by jej** [comment]
Look here: https://github.com/WeActStudio/WeActStudio.MiniSTM32F4x1#where-to-buy

![](https://github.com/WeActStudio/WeActStudio.MiniSTM32F4x1/raw/master/images/STM32F4x1C_Logo&Version.png)

versus

![](https://ae01.alicdn.com/kf/H846d7c4eb99a43f794fb83fe7ad45592W.jpg)

Now it's up to you...
