### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by windskyxb** [WeActTC/WeAct_F411CE#8]
When I execute make board=WeAct_F411CE, I get the following error：

zhouhua@LEGION:~/micropython/ports/stm32$ make BOARD=WeAct_F411CE
Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.
GEN build-WeAct_F411CE/genhdr/qstr.i.last
GEN build-WeAct_F411CE/genhdr/qstr.split
GEN build-WeAct_F411CE/genhdr/qstrdefs.collected.h
QSTR not updated
GEN build-WeAct_F411CE/genhdr/moduledefs.split
GEN build-WeAct_F411CE/genhdr/moduledefs.collected
Module registrations not updated
GEN build-WeAct_F411CE/genhdr/root_pointers.split
GEN build-WeAct_F411CE/genhdr/root_pointers.collected
Root pointer registrations not updated
GEN build-WeAct_F411CE/genhdr/compressed.split
GEN build-WeAct_F411CE/genhdr/compressed.collected
Compressed data not updated
CC boards/WeAct_F411CE/bdev.c
boards/WeAct_F411CE/bdev.c:5:7: error: expected ';' before 'const'
    5 | STATIC const mp_soft_spi_obj_t soft_spi_bus = {
      |       ^~~~~~
      |       ;
-e See https://github.com/micropython/micropython/wiki/Build-Troubleshooting
make: *** [../../py/mkrules.mk:90: build-WeAct_F411CE/boards/WeAct_F411CE/bdev.o] Error 1

![image](https://github.com/WeActStudio/WeAct_F411CE-MicroPython/assets/60282327/213a8d62-ce4a-4722-825e-2f9b07d59163)

**Comment by windskyxb** [comment]
This is a new error when I modify the configuration file to use an external 128Mbit Flash:

zhouhua@LEGION:~/micropython/ports/stm32$ make BOARD=WeAct_F411CE                                                       Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.                                      GEN build-WeAct_F411CE/genhdr/qstrdefs.collected.h                                                                      QSTR not updated                                                                                                        GEN build-WeAct_F411CE/genhdr/moduledefs.collected                                                                      Module registrations not updated                                                                                        GEN build-WeAct_F411CE/genhdr/root_pointers.collected                                                                   Root pointer registrations not updated                                                                                  GEN build-WeAct_F411CE/genhdr/compressed.collected                                                                      Compressed data not updated                                                                                             CC boards/WeAct_F411CE/bdev.c                                                                                           boards/WeAct_F411CE/bdev.c:5:7: error: expected ';' before 'const'                                                          5 | STATIC const mp_soft_spi_obj_t soft_spi_bus = {                                                                       |       ^~~~~~                                                                                                          |       ;                                                                                                         boards/WeAct_F411CE/bdev.c:24:1: error: unknown type name 'STATIC'                                                         24 | STATIC mp_spiflash_cache_t spi_bdev_cache;                                                                            | ^~~~~~                                                                                                          boards/WeAct_F411CE/bdev.c:24:28: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'spi_bdev_cache'          24 | STATIC mp_spiflash_cache_t spi_bdev_cache;                                                                            |                            ^~~~~~~~~~~~~~                                                                       boards/WeAct_F411CE/bdev.c:33:15: error: 'spi_bdev_cache' undeclared here (not in a function); did you mean 'spi_bdev_ioctl'?                                                                                                                      33 |     .cache = &spi_bdev_cache,                                                                                         |               ^~~~~~~~~~~~~~                                                                                          |               spi_bdev_ioctl                                                                                    -e See https://github.com/micropython/micropython/wiki/Build-Troubleshooting                                            make: *** [../../py/mkrules.mk:90: build-WeAct_F411CE/boards/WeAct_F411CE/bdev.o] Error 1

![image](https://github.com/WeActStudio/WeAct_F411CE-MicroPython/assets/60282327/af6fc9b3-e16d-4dec-b22b-9f39b801976c)

**Comment by nesergen** [comment]
> boards/WeAct_F411CE/bdev.c:5:7: error: expected ';' before 'const'
> 5 | STATIC const mp_soft_spi_obj_t soft_spi_bus = {

I have the same error. It was disturbing me a lot of times. But today I have followed the recommendation in stack:
> -e See https://github.com/micropython/micropython/wiki/Build-Troubleshooting

And found the simple solution "To fix this, replace all usages of **STATIC** with **static** in your code (likely a User C Module)."

Search the file **bdev.c** in the folder micropython/ports/stm32/boards/WeAct_F411CE  and rewrite the capital letters to the lower case. 
Compilation finished successfully.
Thank you for this insight !

**Comment by windskyxb** [comment]
> > boards/WeAct_F411CE/bdev.c:5:7: error: expected ';' before 'const'
> > 5 | STATIC const mp_soft_spi_obj_t soft_spi_bus = {
> 
> I have the same error. It was disturbing me a lot of times. But today I have followed the recommendation in stack:
> 
> > -e See https://github.com/micropython/micropython/wiki/Build-Troubleshooting
> 
> And found the simple solution "To fix this, replace all usages of **STATIC** with **static** in your code (likely a User C Module)."
> 
> Search the file **bdev.c** in the folder micropython/ports/stm32/boards/WeAct_F411CE and rewrite the capital letters to the lower case. Compilation finished successfully. Thank you for this insight !

Thank you for your advice! 
After replacing STATIC in bdev.c with static, I successfully compiled the firmware I needed!
